### ISSUE TITLE
text field missing in interface Status definition

### ISSUE THREAD

**Issue by rdhainaut** [abraham/twitter-d#110]
the interface status.d.ts has no text field 
(but has full_text that doesn't exists)

See Example Response for object format at
https://developer.twitter.com/en/docs/twitter-api/v1/tweets/timelines/api-reference/get-statuses-mentions_timeline

```
export interface Status {
  // ...
  full_text: string; // doesn t exist !
  text: string; // field missing
}
```

**Comment by abraham** [comment]
The status type is modeled on a [`?tweet_mode=extended`](https://developer.twitter.com/en/docs/twitter-api/v1/data-dictionary/overview/intro-to-tweet-json#extendedtweet) response with`full_text` which is not truncated to 140 characters like `text` is.

**Comment by rdhainaut** [comment]
@abraham Thanx for your answer so it explains why full_text exists.
But why i can t find "text" field in Status interface https://github.com/abraham/twitter-d/blob/master/types/status.d.ts  ?

**Comment by abraham** [comment]
That's how Twitter built their API. I assume because anything that would be in `text` would also be in `full_text` so it would just be a waste of bandwidth.
