### ISSUE TITLE
User in Status may be trimmed

### ISSUE THREAD

**Issue by takanakahiko** [abraham/twitter-d#25]
For example, statuses / user_timeline allows trim_user.
User information is excluded from Status by specifying trim_user as true.
In other words, I think User should be optional.

See also : https://developer.twitter.com/en/docs/tweets/timelines/api-reference/get-statuses-user_timeline.html

**Comment by abraham** [comment]
I think the approach would be something like defining a `TrimmedUser` (`BaseUser`?) with a limited set of values and `ExtendedUser` (`FullUser`?) and have `User = TrimmedUser || ExtendedUser`.

**Comment by takanakahiko** [comment]
Thank you for your reply!
I misunderstood that "User information will be deleted when trim user specify" .

User type is used by many users
For compatibility, I propose using User / TrimmedUser.
