### ISSUE TITLE
Field text is missing in status

### ISSUE THREAD

**Issue by chasset** [abraham/twitter-d#35]
Hello,

Many thanks to share these declarations.
Why did you remove the text field of a status?
Best regards,

Pierre-Olivier

**Comment by abraham** [comment]
Currently this library is designed to work with [`tweet_mode=extended`](https://developer.twitter.com/en/docs/tweets/tweet-updates.html)

> The text field is no longer included; instead, the payload will contain a field named full_text, which contains the entire untruncated Tweet text.

**Comment by chasset** [comment]
Alright. Thanks.
